/* This file is automatically generated by NRPy+. Do not edit. */

// EVOLVED VARIABLES:
#define NUM_EVOL_GFS 26
#define ADD00GF	0
#define ADD01GF	1
#define ADD02GF	2
#define ADD11GF	3
#define ADD12GF	4
#define ADD22GF	5
#define ALPHAGF	6
#define BETU0GF	7
#define BETU1GF	8
#define BETU2GF	9
#define CFGF	10
#define HDD00GF	11
#define HDD01GF	12
#define HDD02GF	13
#define HDD11GF	14
#define HDD12GF	15
#define HDD22GF	16
#define LAMBDAU0GF	17
#define LAMBDAU1GF	18
#define LAMBDAU2GF	19
#define SFGF	20
#define SFMGF	21
#define TRKGF	22
#define VETU0GF	23
#define VETU1GF	24
#define VETU2GF	25


// AUXILIARY VARIABLES:
#define NUM_AUX_GFS 1
#define HGF	0


// AUXEVOL VARIABLES:
#define NUM_AUXEVOL_GFS 6
#define RBARDD00GF	0
#define RBARDD01GF	1
#define RBARDD02GF	2
#define RBARDD11GF	3
#define RBARDD12GF	4
#define RBARDD22GF	5


// SET gridfunctions_f_infinity[i] = value of gridfunction i in the limit r->infinity:
static const REAL gridfunctions_f_infinity[NUM_EVOL_GFS] = { 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0 };


// SET gridfunctions_wavespeed[i] = gridfunction i's characteristic wave speed:
static const REAL gridfunctions_wavespeed[NUM_EVOL_GFS] = { 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.41421356237310, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0 };


/* PARITY TYPES FOR ALL GRIDFUNCTIONS.
   SEE "Tutorial-Start_to_Finish-Curvilinear_BCs.ipynb" FOR DEFINITIONS. */
const int8_t evol_gf_parity[26] = { 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 0, 4, 5, 6, 7, 8, 9, 1, 2, 3, 0, 0, 0, 1, 2, 3 };
const int8_t aux_gf_parity[1] = { 0 };
const int8_t auxevol_gf_parity[6] = { 4, 5, 6, 7, 8, 9 };
