typedef struct __paramstruct__ {
    REAL Cart_CoM_offsetx;  // grid::Cart_CoM_offsetx
    REAL Cart_CoM_offsety;  // grid::Cart_CoM_offsety
    REAL Cart_CoM_offsetz;  // grid::Cart_CoM_offsetz
    REAL Cart_originx;  // grid::Cart_originx
    REAL Cart_originy;  // grid::Cart_originy
    REAL Cart_originz;  // grid::Cart_originz
    REAL PI;  // BSSN.BSSN_stress_energy_source_terms::PI
    REAL RMAX;  // reference_metric::RMAX
    REAL diss_strength;  // ScalarFieldCollapse::diss_strength
    REAL dxx0;  // grid::dxx0
    REAL dxx1;  // grid::dxx1
    REAL dxx2;  // grid::dxx2
    REAL eta;  // BSSN.BSSN_gauge_RHSs::eta
    REAL f0_of_xx0;  // reference_metric::f0_of_xx0
    REAL f0_of_xx0__D0;  // reference_metric::f0_of_xx0__D0
    REAL f0_of_xx0__DD00;  // reference_metric::f0_of_xx0__DD00
    REAL f0_of_xx0__DDD000;  // reference_metric::f0_of_xx0__DDD000
    REAL f1_of_xx1;  // reference_metric::f1_of_xx1
    REAL f1_of_xx1__D1;  // reference_metric::f1_of_xx1__D1
    REAL f1_of_xx1__DD11;  // reference_metric::f1_of_xx1__DD11
    REAL f1_of_xx1__DDD111;  // reference_metric::f1_of_xx1__DDD111
    REAL f2_of_xx0_xx1;  // reference_metric::f2_of_xx0_xx1
    REAL f2_of_xx0_xx1__D0;  // reference_metric::f2_of_xx0_xx1__D0
    REAL f2_of_xx0_xx1__D1;  // reference_metric::f2_of_xx0_xx1__D1
    REAL f2_of_xx0_xx1__DD00;  // reference_metric::f2_of_xx0_xx1__DD00
    REAL f2_of_xx0_xx1__DD11;  // reference_metric::f2_of_xx0_xx1__DD11
    REAL f2_of_xx1;  // reference_metric::f2_of_xx1
    REAL f2_of_xx1__D1;  // reference_metric::f2_of_xx1__D1
    REAL f2_of_xx1__DD11;  // reference_metric::f2_of_xx1__DD11
    REAL f2_of_xx1__DDD111;  // reference_metric::f2_of_xx1__DDD111
    REAL f3_of_xx0;  // reference_metric::f3_of_xx0
    REAL f3_of_xx0__D0;  // reference_metric::f3_of_xx0__D0
    REAL f3_of_xx0__DD00;  // reference_metric::f3_of_xx0__DD00
    REAL f4_of_xx2;  // reference_metric::f4_of_xx2
    REAL f4_of_xx2__D2;  // reference_metric::f4_of_xx2__D2
    REAL f4_of_xx2__DD22;  // reference_metric::f4_of_xx2__DD22
    REAL invdx0;  // grid::invdx0
    REAL invdx1;  // grid::invdx1
    REAL invdx2;  // grid::invdx2
    REAL xx0;  // grid::xx0
    REAL xx1;  // grid::xx1
    REAL xx2;  // grid::xx2
    REAL xxmax0;  // grid::xxmax0
    REAL xxmax1;  // grid::xxmax1
    REAL xxmax2;  // grid::xxmax2
    REAL xxmin0;  // grid::xxmin0
    REAL xxmin1;  // grid::xxmin1
    REAL xxmin2;  // grid::xxmin2
    int Nxx0;  // grid::Nxx0
    int Nxx1;  // grid::Nxx1
    int Nxx2;  // grid::Nxx2
    int Nxx_plus_2NGHOSTS0;  // grid::Nxx_plus_2NGHOSTS0
    int Nxx_plus_2NGHOSTS1;  // grid::Nxx_plus_2NGHOSTS1
    int Nxx_plus_2NGHOSTS2;  // grid::Nxx_plus_2NGHOSTS2
} paramstruct;
